# Generated by Django 3.1.4 on 2020-12-02 09:18

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('processing_finished', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='', validators=[analytics.models.validate_xls_file])),
                ('status', models.SmallIntegerField(choices=[(1, 'Uploaded'), (2, 'In progress'), (3, 'Done')], default=1)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
