version: '3.8'

services:
  web:
    container_name: perx_app
    build: ./app
    depends_on:
      - redis
    volumes:
      - perx_data:/app/data
      - perx_media:/app/media
      - perx_static:/app/static
    env_file: ./app/perx/.env
    command: gunicorn perx.wsgi:application -w 2 --bind 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    expose:
      - 8000

  redis:
    image: library/redis:alpine
    container_name: perx_redis

  nginx:
    image: library/nginx:1.17.2-alpine
    container_name: perx_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - perx_static:/app/static
    depends_on:
      - web
    ports:
    - 7777:80

  celery:
    build: ./app
    container_name: perx_celery
    command: celery -A perx worker -l INFO
    env_file: ./app/perx/.env
    volumes:
      - perx_data:/app/data
      - perx_media:/app/media
    depends_on:
      - web

volumes:
  perx_data:
  perx_media:
  perx_static: